env:
  es6: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
extends:
  - eslint:recommended
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - prettier
  - "prettier/@typescript-eslint"
plugins:
  - "@typescript-eslint"
rules:
  semi:
    - error
    - never
  complexity:
    - warn
    - max: 10
  no-eval:
    - error
  no-implied-eval:
    - error
  no-magic-numbers:
    - warn
    - ignore: 
      - 0
      - 1
  no-console:
    - warn
  # References for TS rules: https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules
  "@typescript-eslint/explicit-function-return-type":
    - error
    - allowExpressions: true
  "@typescript-eslint/indent":
    - off
  "@typescript-eslint/no-parameter-properties":
    - off
  "@typescript-eslint/no-explicit-any":
    - warn
  "@typescript-eslint/no-use-before-define":
    - off
  "@typescript-eslint/no-inferrable-types":
    - warn
    - ignoreParameters: true
      ignoreProperties: true
  "@typescript-eslint/member-ordering":
    - warn
  "@typescript-eslint/explicit-member-accessibility":
    - error
overrides:
  - files: "**/*.spec.ts"
    env:
      jest: true
    rules:
      "@typescript-eslint/explicit-function-return-type":
        - off
      no-magic-numbers:
        - off
