name: main

on: [push]

jobs:
  test_package:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: build package
        run: |
          npm i
          npm run build

      - name: test package
        run: |
          npm run test
  
  test_demo:
    needs: [test_package]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: example/package-lock.json
  
      - name: build package
        run: |
          npm i
          npm run build

      - name: build demo
        run: |
          cd ./example
          echo "Running in directory $PWD (before npm)"
          npm i
          npm run build

      - name: test demo locally
        run: |
          # test the demo locally:
          cd ./example
          echo "Running in directory $PWD (before npm run test)"
          npm run start & # note intentional use of background shell task https://www.maketecheasier.com/run-bash-commands-background-linux/
          sleep 2 # to give start/webpack a generous amount of time to complete initialization
          npm run test-local

  deploy_package:
    needs: [test_package, test_demo]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: build
        run: |
          npm i
          npm run build

      #- name: debug deploy_package
      #  uses: actions/bin/debug@master

      - name: deploy via semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx semantic-release@17
